[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "bdr-backend"
version = "0.1.0"

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]